services:
  postgres:
    image: postgres14.20-alpine3.23
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - '5672:5672'
      - '9090:15672'

  redis:
    image: redis
    ports:
      - '6379:6379'

  zipkin:
    image: openzipkin/zipkin
    ports:
     - '9411:9411'

#  api-produto:
#    image: api-produto
#    ports:
#      - '8080:8080'
#    depends_on:
#      - postgres
#      - localstack
#      - rabbitmq
#      - redis